name: Deploy Flutter Web to Vercel
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      # Configurar Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      # Obtener dependencias y activar web
      - run: flutter config --enable-web
      - run: flutter pub get
      
      # Construir para web (sin base-href para Vercel)
      - run: |
          flutter build web \
            --dart-define=AUTH_BASE_URL_KEY=${{ secrets.AUTH_BASE_URL_KEY }}
      
      # Instalar Vercel CLI
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      # Desplegar en Vercel
      - name: Deploy to Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./build/web